# Generated by Django 2.2.12 on 2020-08-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorys',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('img', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'verbose_name': 'Product',
            },
        ),
    ]
